<?php

namespace Fatchip\CTPayment;

/**
 * Class CTPaymentMethods
 * @package Fatchip\CTPayment
 */
class CTPaymentMethods
{
    const paymentMethods =
        [
            [
                'name' => 'fatchip_computop_creditcard',
                'shortname' => 'Kreditkarte',
                'description' => 'Computop Kreditkarte',
                'action' => 'FatchipCTCreditCard',
                'template' => '',
                'additionalDescription' => '',
                'className' => 'CreditCard',
                //'countries' => ['DE', 'NL', 'DK', 'FI', 'SE', 'NO'],
            ],
            [
                'name' => 'fatchip_computop_easycredit',
                'shortname' => 'Easycredit',
                'description' => 'Computop Easycredit',
                'action' => 'FatchipCTEasyCredit',
                'template' => 'fatchip_computop_easycredit.tpl',
                'additionalDescription' => 'Rechnungs- und Lieferadresse müssen gleich sein, damit easyCredit genutzt werden kann',
                'className' => 'EasyCredit',
                // 'countries' => ['DE', 'NL', 'DK', 'FI', 'SE', 'NO'],
            ],
            [
                'name' => 'fatchip_computop_ideal',
                'shortname' => 'iDEAL',
                'description' => 'Computop iDEAL',
                'action' => 'FatchipCTIdeal',
                'template' => 'fatchip_computop_ideal.tpl',
                'additionalDescription' => '',
                'className' => 'Ideal',
                //'countries' => ['DE', 'NL', 'DK', 'FI', 'SE', 'NO'],
            ],
            [
                'name' => 'fatchip_computop_klarna_slice_it',
                'shortname' => 'Klarna Slice it',
                'description' => 'Computop Klarna Slice it',
                'action' => 'FatchipCTKlarnaPayments',
                'template' => 'fatchip_computop_klarna_slice_it.tpl',
                'additionalDescription' => '',
                'className' => 'KlarnaPayments',
                //'countries' => ['DE', 'NL', 'DK', 'FI', 'SE', 'NO'],
            ],
            [
                'name' => 'fatchip_computop_klarna_pay_now',
                'shortname' => 'Klarna Pay now',
                'description' => 'Computop Klarna Pay now',
                'action' => 'FatchipCTKlarnaPayments',
                'template' => 'fatchip_computop_klarna_pay_now.tpl',
                'additionalDescription' => '',
                'className' => 'KlarnaPayments',
                //'countries' => ['DE', 'NL', 'DK', 'FI', 'SE', 'NO'],
            ],
            [
                'name' => 'fatchip_computop_klarna_pay_later',
                'shortname' => 'Klarna Pay later',
                'description' => 'Computop Klarna Pay later',
                'action' => 'FatchipCTKlarnaPayments',
                'template' => 'fatchip_computop_klarna_pay_later.tpl',
                'additionalDescription' => '',
                'className' => 'KlarnaPayments',
                //'countries' => ['DE', 'NL', 'DK', 'FI', 'SE', 'NO'],
            ],
            [
                'name' => 'fatchip_computop_lastschrift',
                'shortname' => 'Lastschrift',
                'description' => 'Computop Lastschrift',
                'action' => 'FatchipCTLastschrift',
                'template' => 'fatchip_computop_lastschrift.tpl',
                'additionalDescription' => '',
                'className' => 'Lastschrift',
                //'countries' => ['DE', 'NL', 'DK', 'FI', 'SE', 'NO'],
            ],
            [
                'name' => 'fatchip_computop_mobilepay',
                'shortname' => 'Mobile Pay',
                'description' => 'Computop Mobile Pay',
                'action' => 'FatchipCTMobilepay',
                'countries' => ['DK', 'NO', 'FI', 'SE'],
                'template' => '',
                'additionalDescription' => '',
                'className' => 'MobilePay',
                //'countries' => ['DE', 'NL', 'DK', 'FI', 'SE', 'NO'],
            ],
            [
                'name' => 'fatchip_computop_paydirekt',
                'shortname' => 'Paydirekt',
                'description' => 'Computop Paydirekt',
                'action' => 'FatchipCTPaydirekt',
                'template' => '',
                'additionalDescription' => '',
                'className' => 'Paydirekt',
                //'countries' => ['DE', 'NL', 'DK', 'FI', 'SE', 'NO'],
            ],
            [
                'name' => 'fatchip_computop_paypal_standard',
                'shortname' => 'PayPal',
                'description' => 'Computop PayPal Standard',
                'action' => 'FatchipCTPaypalStandard',
                'template' => '',
                'additionalDescription' => '',
                'className' => 'PaypalStandard',
                //'countries' => ['DE', 'NL', 'DK', 'FI', 'SE', 'NO'],
            ],
            [
                'name' => 'fatchip_computop_paypal_express',
                'shortname' => 'PayPalExpress',
                'description' => 'Computop PayPal Express',
                'action' => 'FatchipCTPaypalExpress',
                'template' => '',
                'additionalDescription' => '',
                'className' => 'PaypalExpress',
                //'countries' => ['DE', 'NL', 'DK', 'FI', 'SE', 'NO'],
            ],
            [
                'name' => 'fatchip_computop_postfinance',
                'shortname' => 'Postfinance',
                'description' => 'Computop Postfinance',
                'action' => 'FatchipCTPostFinance',
                'template' => '',
                'additionalDescription' => '',
                'className' => 'PostFinance',
                //'countries' => ['DE', 'NL', 'DK', 'FI', 'SE', 'NO'],
            ],
            [
                'name' => 'fatchip_computop_przelewy24',
                'shortname' => 'Przelewy24',
                'description' => 'Computop Przelewy24',
                'action' => 'FatchipCTPrzelewy24',
                'countries' => ['PL',],
                'template' => '',
                'additionalDescription' => '',
                'className' => 'Przelewy24',
                //'countries' => ['DE', 'NL', 'DK', 'FI', 'SE', 'NO'],
            ],
            [
                'name' => 'fatchip_computop_sofort',
                'shortname' => 'SOFORT',
                'description' => 'Computop SOFORT',
                'action' => 'FatchipCTSofort',
                //'template' => 'fatchip_computop_sofort.tpl',
                'template' => '',
                'additionalDescription' => '',
                'className' => 'Sofort',
                //'countries' => ['DE', 'NL', 'DK', 'FI', 'SE', 'NO'],
            ],
            [
                'name' => 'fatchip_computop_amazonpay',
                'shortname' => 'AmazonPay',
                'description' => 'Computop AmazonPay',
                'action' => 'FatchipCTAmazon',
                'template' => '',
                'additionalDescription' => '',
                'className' => 'AmazonPay',
                //'countries' => ['DE', 'NL', 'DK', 'FI', 'SE', 'NO'],
            ],
            [
                'name' => 'fatchip_computop_afterpay_invoice',
                'shortname' => 'AfterpayInvoice',
                'description' => 'Computop Afterpay Rechnung',
                'action' => 'FatchipCTAfterpay',
                'template' => 'fatchip_computop_afterpay_invoice.tpl',
                'additionalDescription' => '',
                'className' => 'Afterpay',
                //'countries' => ['DE', 'NL', 'DK', 'FI', 'SE', 'NO'],
            ],
            [
                'name' => 'fatchip_computop_afterpay_installment',
                'shortname' => 'AfterpayInstallment',
                'description' => 'Computop Afterpay Ratenzahlung',
                'action' => 'FatchipCTAfterpay',
                'template' => 'fatchip_computop_afterpay_installment.tpl',
                'additionalDescription' => '',
                'className' => 'Afterpay',
                //'countries' => ['DE', 'NL', 'DK', 'FI', 'SE', 'NO'],
            ],
        ];
}
